# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParsingJson_SwiftyJson' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ParsingJson_SwiftyJson

pod 'SwiftyJSON'

  target 'ParsingJson_SwiftyJsonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParsingJson_SwiftyJsonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
